AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
  - 'spec/**/*'
  - 'test/**/*'
  - 'app/mailers/application_mailer.rb'
  - 'app/models/application_record.rb'
  - 'config/application.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'bin/setup'
  - 'bin/update'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/LineLength:
  Max: 130
