AllCops:
  Exclude:
  - 'vendor/**/*'
  - 'db/schema.rb'
  - 'db/migrate/*.rb'
  - 'spec/rails_helper.rb'
  - 'spec/spec_helper.rb'

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
  - 'spec/**/*'
  - 'test/**/*'
  - 'app/mailers/application_mailer.rb'
  - 'app/models/application_record.rb'
  - 'config/application.rb'

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'bin/setup'
  - 'bin/update'

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Exclude:
    - 'config/**/**'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Exclude:
  - 'config/**/**'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Exclude:
  - 'config/**/**'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 25

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Naming/AsciiIdentifiers:
  Exclude:
    - 'spec/**/*'
